
theme = "gruvbox_dark_hard_transparent"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = [ "mode", "spinner", "diagnostics", "file-name" ]
center = [ "version-control" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL MODE LAH 💀"
mode.insert = "INSERT MODE BRO 🔥"
mode.select = "SELECT MODE LUL ✅"

[keys.normal]
"backspace" = "delete_char_backward"
C-f = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
